# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Graduate-live' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'YYKit'
pod 'SnapKit'
pod 'SDWebImage'
pod 'Alamofire'
  # Pods for Graduate-live

end
